# dbt_project.yml

# Consider renaming 'my_new_project' to something more specific like 'deel_assignment_dbt'
# If you change it here, also change the key under the 'models:' block below.
name: 'my_new_project' 
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
# Ensure 'default' matches your dbt Cloud connection profile name.
profile: 'default' 

# Define paths for dbt resources. These defaults are usually fine.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Define where compiled code and artifacts are stored.
target-path: "target" 
# Define directories to be removed by `dbt clean`.
clean-targets:        
  - "target"
  - "dbt_packages"


# Configuring models: Set default materializations by directory.
# This improves organization and avoids needing config blocks in every model file.
models:
  # This key MUST match the 'name:' specified at the top of this file.
  my_new_project: 
    # Default materialization for models placed directly in /models (if any)
    # +materialized: view # (Optional: uncomment if you have models directly in /models)

    # Configuration for models within the /models/staging directory
    staging:
      +materialized: view # Staging models are typically views

    # Configuration for models within the /models/intermediate directory
    intermediate:
      +materialized: view # Intermediate models are often views or ephemeral

    # Configuration for models within the /models/marts directory
    marts:
      +materialized: table # Mart models (dims, facts) are often tables for performance
